Grading at 12/03/2022:22:01:38.741377
For commit ID 15bcfe8cdd2db060f46326c17acdc96fd5a23506
Grading at Sat Dec  3 05:01:31 PM EST 2022
Doing some basic checking for your submission

Step 1
Checking that cyoa-step1 compiles
g++ -o cyoa-step1 -std=gnu++98 -Werror -Wall -pedantic -ggdb3 cyoa-step1.cpp
The code compiled (good)
Executable cyoa-step1 exists (good)
------------------------------------
Now running YOUR tests for step 1
------------------------------------


1.1: Current test is ./cyoa-step1 numfault1 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
terminate called after throwing an instance of 'InvalidInputLine'
  what():  Invalid input line!

timeout: the monitored command dumped core
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.2: Current test is ./cyoa-step1 numfault2 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
terminate called after throwing an instance of 'InvalidInputLine'
  what():  Invalid input line!

timeout: the monitored command dumped core
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.3: Current test is ./cyoa-step1 numfault3 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
terminate called after throwing an instance of 'NumOutOfRange'
  what():  Number out of range!

timeout: the monitored command dumped core
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.4: Current test is ./cyoa-step1 goodstory < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean
No request to check for intermediate deadline completion on step 1

Step 2
Checking that cyoa-step2 compiles
g++ -o cyoa-step2 -std=gnu++98 -Werror -Wall -pedantic -ggdb3 cyoa-step2.cpp	
The code compiled (good)
Executable cyoa-step2 exists (good)
------------------------------------
Now running YOUR tests for step 2
------------------------------------
No request to check for intermediate deadline completion on step 2

Step 3
Checking that cyoa-step3 compiles
g++ -o cyoa-step3 -std=gnu++98 -Werror -Wall -pedantic -ggdb3 cyoa-step3.cpp
The code compiled (good)
Executable cyoa-step3 exists (good)
------------------------------------
Now running YOUR tests for step 3
------------------------------------


3.1: Current test is ./cyoa-step3 goodstory < /dev/null
-----------------------------
We considered this a failure case.
But you did not (exit status was EXIT_SUCCESS).
No request to check for intermediate deadline completion on step 3

Step 4
Checking that cyoa-step4 compiles
g++ -o cyoa-step4 -std=gnu++98 -Werror -Wall -pedantic -ggdb3 cyoa-step4.cpp
The code compiled (good)
Executable cyoa-step4 exists (good)
------------------------------------
Now running YOUR tests for step 4
------------------------------------
No request to check for intermediate deadline completion on step 4

You have NOT passed your test cases!
You should go and figure out/understand where thing went wrong
And fix the problem(s) before the deadline

Overall Grade: NO GRADE YET
